### ISSUE TITLE
Delete buttons don't work

### ISSUE THREAD

**Issue by uguntde** [opto/Text-Insert#1]
If I press a delete button to remove a shortcut nothings happens.
Using TB 102.2.1

**Comment by opto** [comment]
thanks for observing. Have fixed the bug, will upload later today, because I need to remove some experimental code for a new feature.

**Comment by opto** [comment]
has been corrected and uploaded in new versions

**Comment by uguntde** [comment]
it now works great

**Comment by uguntde** [comment]
There is a remaining bug: If you delete a line, it is deleted from the screen. But if you enter a new line with the same short-cut it will be appended to the old line and two lines appear in the setup window. In the insertion however only one line appears. The work-around is to close the setup window and restart it.
